apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "service-chart.fullname" . }}-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ template "service-chart.fullname" . }}-converstionrate
  template:
    metadata:
      labels:
        app: {{ template "service-chart.fullname" . }}-converstionrate
    spec:
      containers:
        - name: {{ template "service-chart.fullname" . }}-converstionrate
          image: vishesh30/qtyconverstion:1.0.19
          env:
            - name: POSTGRES_HOST
              value: postgres://postgres:12345@postgres:5432/qty-converstion-dev

---

kind: Service
apiVersion: v1
metadata:
  name: {{ template "service-chart.fullname" . }}-service
spec:
  type: NodePort
  selector:
    app: {{ template "service-chart.fullname" . }}-converstionrate
  ports:
    - port: 8080
      targetPort: 3000

---

apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "postgres-config"
  namespace: "default"
  labels:
    app: "postgres"
data:
  POSTGRES_DB: "qty-converstion-dev"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "12345"

---

apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "postgres"
  namespace: "default"
  labels:
    app: "postgres"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "postgres"
  template:
    metadata:
      labels:
        app: "postgres"
    spec:
      containers:
      - name: "postgres"
        image: "postgres:9.6.2"
        env:
        - name: "POSTGRES_DB"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_DB"
              name: "postgres-config"
        - name: "POSTGRES_USER"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_USER"
              name: "postgres-config"
        - name: "POSTGRES_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_PASSWORD"
              name: "postgres-config"
        ports:
          - containerPort: 5432
            name: postgres
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/db-data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres