apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "service-chart.fullname" . }}-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ template "service-chart.fullname" . }}-converstionrate
  template:
    metadata:
      labels:
        app: {{ template "service-chart.fullname" . }}-converstionrate
    spec:
      containers:
        - name: {{ template "service-chart.fullname" . }}-converstionrate
          image: vishesh30/qtyconverstion:1.0.2
          env:
            - name: DB_URL
              value: postgres://{{ template "postgres.fullname" . }}.default.svc.cluster.local:5432/{{ .Values.DbName }}

---

kind: Service
apiVersion: v1
metadata:
  name: {{ template "service-chart.fullname" . }}-service
spec:
  type: NodePort
  selector:
    app: {{ template "service-chart.fullname" . }}-converstionrate
  ports:
    - port: 8080
      targetPort: 3000